# Replace /path/to/python/bin path with actual Python path on your system
- name: Set Python path
  hosts: your_hosts
  become: true
  tasks:
    - name: Add Python path to .bashrc
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: 'export PATH="/path/to/python/bin:$PATH"'
        state: present
